from __future__ import annotations


class AcquiringException(Exception):
    pass
